version: "3.8"
services:
  curtain:
    tty: true
    stdin_open: true
    restart: unless-stopped
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-curtain
    container_name: production_curtain
    ports:
      - "80:80"
      - "443:443"
    networks:
      - curtain-net
  cactus:
    restart: unless-stopped
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-cactus
    container_name: production_cactus
    networks:
      - curtain-net
    volumes:
      - type: bind
        source: ./files
        target: /app/cactus/files
      - type: bind
        source: ./db
        target: /app/cactus/db
networks:
  curtain-net:

