version: "3.8"
services:
  curtain:
    tty: true
    stdin_open: true
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-curtain
    container_name: production_curtain
    ports:
      - 80:80
    networks:
      - curtain-net
  cactus:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-cactus
    container_name: production_cactus
    networks:
      - curtain-net
networks:
  curtain-net:

