version: "3.8"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port

    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - curtain-net
  curtain:
    tty: true
    stdin_open: true
    restart: unless-stopped
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-curtain
    container_name: production_curtain
    ports:
      - "8080:80"
      - "4433:443"
    networks:
      - curtain-net
  cactus:
    restart: unless-stopped
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-cactus
    container_name: production_cactus
    networks:
      - curtain-net
    volumes:
      - type: bind
        source: ./files
        target: /app/cactus/files
      - type: bind
        source: ./db
        target: /app/cactus/db
networks:
  curtain-net:

